ci:
  autofix_prs: false
  autoupdate_schedule: 'monthly'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        # Prevent giant files from being committed.
      - id: check-ast
        # Simply check whether files parse as valid python.
      - id: check-case-conflict
        # Check for files with names that would conflict on a case-insensitive
        # filesystem like MacOS HFS+ or Windows FAT.
      - id: check-json
        # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict
        # Check for files that contain merge conflict strings.
      - id: check-symlinks
        # Checks for symlinks which do not point to anything.
      - id: check-toml
        # Attempts to load all TOML files to verify syntax.
      - id: check-xml
        # Attempts to load all xml files to verify syntax.
      - id: check-yaml
        # Attempts to load all yaml files to verify syntax.
      - id: debug-statements
        # Check for debugger imports and py37+ breakpoint() calls in python
        # source.
      - id: detect-private-key
        # Checks for the existence of private keys.
      - id: double-quote-string-fixer
        # Replace double-quoted strings with single-quoted strings.
      - id: end-of-file-fixer
        # Makes sure files end in a newline and only a newline.
        exclude: ".*(svg.*|extern.*)$"
      - id: trailing-whitespace
        # Trims trailing whitespace.
        exclude: ".*(data.*|extern.*)$"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        # Prevent common mistakes of assert mck.not_called(), assert
        # mck.called_once_with(...) and mck.assert_called.
      - id: rst-directive-colons
        # Detect mistake of rst directive not ending with double colon.
      - id: rst-inline-touching-normal
        # Detect mistake of inline code touching normal text in rst.
      - id: text-unicode-replacement-char
        # Forbid files which have a UTF-8 Unicode replacement character.
      - id: python-check-blanket-noqa
        # Enforce that all noqa annotations always occur with specific codes.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.4"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/scientific-python/cookie
    rev: 2025.01.22
    hooks:
      - id: sp-repo-review

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
      - id: isort
        name: isort (cython)
        types: [cython]
        additional_dependencies: [toml]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--ignore", "E501,W503"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes", "--ignore-words-list", "exten, conver, fom"]
        additional_dependencies:
          - tomli

  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
      - id: numpydoc-validation
        exclude: "extern/"

  # temporarily use commit from master branch until the next release
  # see https://github.com/PyCQA/docformatter/pull/287
  - repo: https://github.com/PyCQA/docformatter
    rev: 06907d0267368b49b9180eed423fae5697c1e909
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
        exclude: "extern/"

  # - repo: https://github.com/MarcoGorelli/absolufy-imports
  #   rev: v0.3.1
  #   hooks:
  #   - id: absolufy-imports
