name: photutils

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - jupyter
    - matplotlib
    - numpy
    - scikit-image
    - scikit-learn
    - scipy
    - docutils
    - Sphinx >=1.5.1,<=1.5.6
