version: 2

jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux2014_i686:2022-04-03-da6ecb3
    steps:
      - checkout
      - run:
          name: Install dependencies for Python 3.9
          command: /opt/python/cp39-cp39/bin/pip install tox
      - run:
          name: Run tests for Python 3.9
          command: |
            stty rows 50 cols 80
            /opt/python/cp39-cp39/bin/python -m tox -e circleci_32bit
